Add types to mapType
progrium/macdriver pull request #149
Opened 2023-07-19 15:26 UTC by programmingkidx

A lot of methods are skipped by the wrapper generation system because the type they return on not in the mapType() function. To increase the number of Objective-C methods that are wrapped this patch adds support for these types: 
- char
- short 
- float
- double
- long
- long long
- uint32_t
- size_t

2023-07-19 22:47 UTC, programmingkidx commented
I wasn't sure if I should include changes to generated files so I will include them here.

[0001-more-types.patch](https://github.com/progrium/macdriver/files/12100653/0001-more-types.patch)

2023-07-20 20:31 UTC, tmc commented
@programmingkidx instead of attaching a patch could you push a commit?

2023-07-28 17:59 UTC, programmingkidx commented
Is there anything else stopping this pull request from being merged?

2023-07-28 19:06 UTC, progrium commented
@tmc look good?

2023-07-29 01:32 UTC, tmc approved these changes
LGTM

2023-07-29 01:33 UTC, tmc requested changes
erh there seems to be a problem:

Error: core/core_objc.gen.go:4886:2: x redeclared in this block
Error: 	core/core_objc.gen.go:4883:7: other declaration of x

2023-07-29 04:19 UTC, programmingkidx commented
This is the error I see when I try to build a program with this commit in place:
```
macdriver/core/core_objc.gen.go:4960:2: x redeclared in this block
macdriver/core/core_objc.gen.go:4957:7: other declaration of x
macdriver/core/core_objc.gen.go:4966:10: cannot convert x (variable of type gen_NSObject) to type C.uint
```

I traced the issue to a method called ProvideImageDataBytesPerRowOrigin(). According to the documentation there is no method with this name. There is one called provideImageData:bytesPerRow:origin::size::userInfo:. I'm guessing this is a bug.

My first idea to fix this issue was to open the json file for NSObject and change the argument's name from x to x1. Problem is there is no json file.

I then did a grep search. It showed ProvideImageDataBytesPerRowOrigin to only be in the core/core_objc.gen.go file, so this means I am not sure where this method comes from.

@tmc Any idea where the ProvideImageDataBytesPerRowOrigin() method comes from?

2023-07-30 19:11 UTC, programmingkidx commented
I found where ProvideImageDataBytesPerRowOrigin() comes from. It is from api/objectivec/nsobject.objc.json. I fixed the problem by changing the name of the receiver variable.

2023-07-30 19:22 UTC, programmingkidx commented
The current problem with this pull request is with a method called preservationPriorityForTag:. This is the error I see:

macdriver/cocoa/cocoa_objc.gen.go:742:3: error: 'preservationPriorityForTag:' is unavailable: not available on macOS
                preservationPriorityForTag: tag];

This is an issue with the API_UNAVAILABLE() macro. MacDriver does not currently have a system in place to handle this situation.

2023-08-08 16:37 UTC, progrium commented
Not sure how this issue fell out of the documented change proposed. Maybe that it opened up new methods to be supported that introduced these errors? Anyway, I made sure these types are supported in darwinkit, so I'm closing this PR. Thanks!

2023-08-08 16:37 UTC, closed without merging